/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package it.unisannio.lm.ids.classmates.commons

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
