/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package it.unisannio.lm.ids.classmates.commons

import org.amshove.kluent.`should be equal to`
import org.spekframework.spek2.Spek
import org.spekframework.spek2.style.specification.describe


object LibraryTest : Spek({
    describe("test") {
        it("non so") {
            true `should be equal to` true
        }
    }
})
